[package]
name = "lsc"
description = "Lightscript compiler"
version = "0.1.0"
authors = ["Jack <jbass2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
